### ISSUE TITLE
Missing full stops 

### ISSUE THREAD

**Issue by alextfish** [asilano/free-dom#109]
A few full stops are missing in:

Trader's description before the /
Trader's log for Silvers gained
Crossroads's log for actions gained
Ill-Gotten Gains's log for curses gained
Nomad Camp's description (cf Woodcutter)
Scheme's "had nothing to return" case (will matter when Procession is implemented)
Spice Merchant's description
Stables's discard logs

**Comment by asilano** [comment]
Ha! Fixing these up has made CodeClimate report a worsening of Margrave and Stables - because their log-lines are now (correctly) identical.
