### ISSUE TITLE
Proofreading/editing/consistency edits - Base game

### ISSUE THREAD

**Issue by alextfish** [asilano/free-dom#114]
Militia's "+2 cash" should be capitalised.

More arguably, Library's "Set Aside" button text shouldn't have the A capitalised. Cf Spy's buttons saying  "Put back", "Do nothing" etc; but also cf Thief's "Just Trash" / "Trash and Take".

**Comment by asilano** [comment]
Fixing Militia and Library. My excuse for Thief is that Trash is a terminology word, and Take gets a capital for symmetry.
